export const VIDEO_CATALOG=[
 {id:'scan-playmaker',icon:'👀',category:'tactique',skill:'Vision',title:'Scanner avant la réception',focus:'Prise d’information',duration:12,url:'https://www.youtube.com/results?search_query=football+midfielder+scanning+before+receiving',instruction:'Observe uniquement les secondes qui précèdent la réception du ballon.',tags:['scan','orientation','vision'],questions:['Combien de scans le joueur effectue-t-il avant de recevoir ?','À quel moment arrive son dernier regard ?','Que découvre-t-il derrière son épaule ?','Son premier contrôle utilise-t-il cette information ?'],fieldMission:'Sur 20 réceptions, réaliser au moins deux scans avant le contrôle.'},
 {id:'body-first-touch',icon:'↗️',category:'technique',skill:'Contrôle',title:'Orientation et premier contrôle',focus:'Corps ouvert et contrôle utile',duration:12,url:'https://www.youtube.com/results?search_query=football+first+touch+body+orientation+midfielder',instruction:'Observe le bassin, les épaules, le pied d’appui et la direction du premier contact.',tags:['premier contrôle','corps ouvert','pied opposé'],questions:['Le joueur est-il déjà ouvert avant la passe ?','Quel pied reçoit le ballon et pourquoi ?','Le contrôle éloigne-t-il le ballon de la pression ?','Combien de touches avant l’action suivante ?'],fieldMission:'Réaliser 30 contrôles orientés vers l’espace libre avec le pied opposé.'},
 {id:'final-pass',icon:'🎯',category:'tactique',skill:'Décision',title:'Créer la passe qui casse une ligne',focus:'Fixer puis libérer',duration:15,url:'https://www.youtube.com/results?search_query=attacking+midfielder+final+pass+decision+making',instruction:'Analyse le déclencheur de la passe et les options disponibles.',tags:['passe finale','fixation','tempo'],questions:['Quelles options existent au moment de la réception ?','Quel adversaire est fixé avant la passe ?','Pourquoi cette passe est-elle préférable ?','Le joueur aurait-il pu jouer plus tôt ?'],fieldMission:'Créer 10 situations : fixer un défenseur puis jouer dans le dos de la ligne.'},
 {id:'off-ball-10',icon:'🏃',category:'tactique',skill:'Jeu sans ballon',title:'Se rendre disponible entre les lignes',focus:'Déplacements invisibles',duration:15,url:'https://www.youtube.com/results?search_query=attacking+midfielder+off+the+ball+movement+analysis',instruction:'Suis le joueur lorsqu’il ne touche pas le ballon.',tags:['démarquage','interligne','soutien'],questions:['Quand quitte-t-il sa zone ?','Comment change-t-il de rythme ?','Que fait-il après avoir passé ?','Son déplacement crée-t-il un espace pour un partenaire ?'],fieldMission:'Après chaque passe, recréer immédiatement une nouvelle ligne de soutien.'},
 {id:'change-pace',icon:'⚡',category:'physique',skill:'Explosivité',title:'Changer de rythme au bon moment',focus:'Premiers appuis explosifs',duration:10,url:'https://www.youtube.com/results?search_query=football+change+of+pace+attacking+midfielder',instruction:'Observe le geste ou l’information qui déclenche l’accélération.',tags:['accélération','appuis','rythme'],questions:['Quel événement déclenche l’accélération ?','Les trois premiers appuis sont-ils courts et puissants ?','Le joueur protège-t-il le ballon pendant l’accélération ?','Quand ralentit-il de nouveau ?'],fieldMission:'Après chaque feinte réussie, accélérer franchement pendant trois appuis.'},
 {id:'self-match',icon:'🎥',category:'auto',skill:'Vision',title:'Analyser mon propre match',focus:'Preuves personnelles',duration:20,url:'',instruction:'Choisis cinq séquences où tu reçois entre les lignes et compare tes décisions.',tags:['ma vidéo','match','auto-évaluation'],questions:['Avais-tu scanné avant la réception ?','Ton corps permettait-il de jouer vers l’avant ?','Quelle option n’as-tu pas vue ?','Quelle décision veux-tu répéter ou corriger ?'],fieldMission:'Rejouer mentalement cinq situations et définir une consigne unique pour le prochain match.'}
];
export function videoById(id){return VIDEO_CATALOG.find(v=>v.id===id)}
export function videoForPlan(plan){const t=`${plan?.kind||''} ${plan?.title||''} ${(plan?.blocks||[]).map(b=>b.title).join(' ')}`.toLowerCase();if(/vitesse|sprint|explos|accél/.test(t))return videoById('change-pace');if(/contrôle|technique|ballon/.test(t))return videoById('body-first-touch');if(/passe|vision|scan/.test(t))return videoById('scan-playmaker');return videoById('off-ball-10')}
